---
title: "Ordering"
format: html
editor: visual

vignette: >
  %\VignetteIndexEntry{Ordering}
  %\VignetteEngine{quarto::html}
  %\VignetteEncoding{UTF-8}
---

Ordering capabilities are available in the package module server.

From version [0.8.0](../news/index.html#kitems-v080), how to sort the items is now defined in the YAML config file with a single `sort` entry.\
It takes an instruction that will be analyzed to get the attribute ranking as well as the direction:

`sort: date, desc(total)`

This instruction will first order items by (ascending) `date`, then descending `total`.

Allowing multiple rules is there to help sorting items that it would not be possible to order given the first rule. No limit is set, but two or three rules should be enough. If not, you may want to consider adding a specific attribute (most probably a skipped & hidden one) with a computed value to help with ranking. Then you can set the rule on this attribute.

You can set / update the ordering instruction in the Admin Console.

::: callout-note
The ordering is applied at the main filtering layer level.
:::

## Useful links

- Data model structure – [core concepts](./core-concepts.html#structure)
- Admin console – [admin](./admin.html#data-model)
