

#' Insert Item(s)
#'
#' @param values a data.frame of item(s) to insert.
#' @param items a data.frame of items where to insert.
#'
#' @details
#' The function is mostly a wrapper around [dplyr::bind_rows()] function.
#'
#' It does check for potential duplicates among the 'id' column.
#' If so, the opeartion will be aborted as there is no way to know how to
#' fix the duplicated id(s).
#'
#' @returns a data.frame.
#' @export
#'
#' @examples
#' \dontrun{
#' insert(values, items)}

insert <- function(values, items){

  # ////////////////////////////////////////////////////////////////////////////
  # -- secure against duplicated ids
  # (in case duplicated values are generated by data.model defaults)
  if(any(duplicated(values$id)))
    stop("Duplicated ids have been generated, insert is aborted!")

  # -- insert item(s)
  # Need to check for empty items, otherwise an error will be raised by dplyr
  items <- if(is.null(items) || nrow(items) == 0) as.data.frame(values) else dplyr::bind_rows(items, values)
  catl("- Rows inserted, output dim =", dim(items), level = 2)

  # -- return
  items

}
