

#' Insert Item(s)
#'
#' @param values a data.frame of item(s) to insert.
#' @param items a data.frame of items where to insert.
#'
#' @returns a data.frame of the items
#' @export
#'
#' @examples
#' \dontrun{
#' rows_insert(items, values)}

rows_insert <- function(values, items){

  # ////////////////////////////////////////////////////////////////////////////
  # -- secure against duplicated ids
  # (in case duplicated values are generated by data.model defaults)
  if(any(duplicated(values$id)))
    stop("Duplicated ids have been generated, insert is aborted!")

  # -- insert item(s)
  # Need to check for empty items, otherwise an error will be raised by dplyr
  items <- if(nrow(items) == 0) as.data.frame(values) else dplyr::bind_rows(items, values)
  catl("- Rows inserted, output dim =", dim(items), level = 2)

  # -- return
  items

}
