

#' Insert Item(s)
#'
#' @param items a data.frame of the items.
#' @param values a list of named values.
#' @param data.model a data.frame of the data.model.
#'
#' @details
#' values is a named list. The names are used to check the corresponding values
#' vs the data.model (class, default values if the provided one are not valid).
#' The elements in the list must have either length one or same length as the id element.
#'
#' When an element has length one but the id has several values, all items corresponding
#' to these ids will be updated with same value. To do so, values will be turned into
#' a data.frame using as.data.frame ; for this reason, it's strongly advised to wrap
#' the call into tryCatch as this may fail.
#'
#' @returns a data.frame of the items
#' @export
#'
#' @examples
#' \dontrun{
#' rows_insert(items, values, data.model)}

rows_insert <- function(items, values, data.model){

  # ////////////////////////////////////////////////////////////////////////////
  # -- cleanup & prepare values

  # -- drop unmatched columns
  # before projection to avoid potential duplicated rows
  values <- values[names(values) %in% data.model$name]

  # -- secure against length 0 (NULL, numeric(0)...)
  # otherwise as.data.frame will fail
  if(any(lengths(values) == 0))
    values <- values[lengths(values) != 0]

  # -- make rectangular
  # elements must have length 1 or same as the id element
  values <- as.data.frame(values)

  # -- secure against existing id(s)
  if(any(values$id %in% items$id)){
    values <- values[!values$id %in% items$id, ]
    if(nrow(values) == 0)
      stop("Nothing to insert: duplicated id(s)")
    else
      warning("Rows with duplicated id(s) removed!")}

  # -- secure against missing columns
  if(any(!data.model$name %in% names(values))){
    catl("- Adding missing columns", level = 2)
    values[data.model$name[!data.model$name %in% names(values)]] <- NA}


  # ////////////////////////////////////////////////////////////////////////////
  # -- check values & types

  values <- sapply(names(values),
                   function(x) attribute_value(key = x,
                                               value = values[[x]],
                                               data.model = data.model),
                   simplify = FALSE,
                   USE.NAMES = TRUE)


  # ////////////////////////////////////////////////////////////////////////////
  # -- final check
  # (in case duplicated ids are generated by data.model defaults)
  if(any(duplicated(values$id)))
    stop("Duplicated ids have been generated, insert is aborted!")

  # -- insert item(s)
  # Need to check for empty items, otherwise an error will be raised by dplyr
  items <- if(nrow(items) == 0) as.data.frame(values) else dplyr::bind_rows(items, values)
  catl("- Rows inserted, output dim =", dim(items), level = 2)

  # -- return
  items

}
