

#' Insert Item(s)
#'
#' @param items a data.frame of the items.
#' @param values a list of named values.
#'
#' @details
#' values is a named list. The names are used to check the corresponding values
#' vs the data.model (class, default values if the provided one are not valid).
#' The elements in the list must have either length one or same length as the id element.
#'
#' When an element has length one but the id has several values, all items corresponding
#' to these ids will be updated with same value. To do so, values will be turned into
#' a data.frame using as.data.frame ; for this reason, it's strongly advised to wrap
#' the call into tryCatch as this may fail.
#'
#' @returns a data.frame of the items
#' @export
#'
#' @examples
#' \dontrun{
#' rows_insert(items, values)}

rows_insert <- function(items, values){

  # ////////////////////////////////////////////////////////////////////////////
  # -- secure against duplicated ids
  # (in case duplicated values are generated by data.model defaults)
  if(any(duplicated(values$id)))
    stop("Duplicated ids have been generated, insert is aborted!")

  # -- insert item(s)
  # Need to check for empty items, otherwise an error will be raised by dplyr
  items <- if(nrow(items) == 0) as.data.frame(values) else dplyr::bind_rows(items, values)
  catl("- Rows inserted, output dim =", dim(items), level = 2)

  # -- return
  items

}
